#+STARTUP: showall indent hidestars

* What is it?

Это учебный файловый вирус, под Linux.

* License

GNU General Public License v.2.

* Purprose

Для ознакомления с работой бинарных файлов, процессов загрузки и
линковки.

* What it does?

Заражает первый ELF-файл, расположенный в одной с ним директории.

* How can I use it?

** Simple and fast way

[TODO:gmm] - набор команд, которые сделают все за юзера:

#+BEGIN_SRC sh
  ...
#+END_SRC

** Hard way

- Install Emacs - orgmode (part of Emacs) need for generate code files
  from literate source file
- Press Alt+x and type ~org-babel-tangle~ elisp-function (you can just
  press ~C-c C-v t~ instead) to generate source code files. Will be
  generated:
  - source code of virus
  - several victim's source code.
  If you skip this step, you can get generated files from [TODO:gmm] -
  WHERE? - folder. Copy this files to root folder of project.
- make
- run virus: ./virus
- Go to section [[*How it works and how I see it][How it works and how I see it]]
- Learn russian (becouse it`s a hacker's language like assembler and
  leetspeak)
- Open literate source and read it
- Contribute (Pull Requests are welcome)

* How it works and how I see it

Выберете любой бинарник мишени. Вам нужно убедиться, что заражение
действительно состоялось. Если это так - у файла изменится адрес точки
входа.
Так выглядит точка входа мишени ~hello~ до заражения файла:

#+BEGIN_SRC sh
  $ readelf -h hello | grep Адрес

  Адрес точки входа:               0x400550
#+END_SRC

Запустите мишень, убедитесь, что она работает:

#+BEGIN_SRC sh
  $ ./hello

  Hello world!
  Current local time and date: Tue Mar  2 02:35:00 2021
#+END_SRC

Запустите вирус, вы увидите лог заражения - какие файлы вирус поптылася
заразить - и какой файл в итоге заразил:

#+BEGIN_SRC sh
  $ ./virus

  asm file: infection try
  hello file: infection try
  hello is successfully infected
#+END_SRC

Так выглядит точка входа мишени ~hello~ после заражения:

#+BEGIN_SRC sh
  $ readelf -h hello | grep Адрес

  Адрес точки входа:               0x802b28
#+END_SRC

Запустите зараженный файл, чтоб убедиться, что он не сломан:

#+BEGIN_SRC sh
  $ ./hello

  asm file: infection try
  hello file: infection try
  .#ex2.txt file: infection try
  final_version.org file: infection try
  hello_stripped file: infection try
  hello_stripped is successfully infected
  Hello world!
  Current local time and date: Tue Mar  2 02:30:18 2021
#+END_SRC

Вы видите лог заражения, какой файл в итоге был заражен, и вывод ~printf~
из самой жертвы.

Заражение прошло успешно.

Учтите, что вирус заражает ближайший незараженный файл. Поэтому если
выбранная вами мишень не заразилась сразу же, просто продолжайте
запускать вирус, пока он не дойдет до вашей мишени.

* Libs and Details

Для создания мишеней для заражения проект использует утилиты ELFkickers,
чей код был скачан отсюда
http://www.muppetlabs.com/~breadbox/software/elfkickers.html и может
распространяться и модифицироваться согласно GNU GPL v.2

** Makefile's targets:

- ~all~ - выполняет все ниже указанные цели кроме clean
- ~virus~ - компилирует файл вируса, если он есть
- ~sstrip~ - компилирует утилиты ELFkickers
- ~victims~ - компилирует все тестовые мешени по два раза, чтоб дубликат
каждой мишени можно было стрипнуть
- ~stripped_victims~ удаляет заголвоки секций из каждого дубликата
  мишени. Таким образом есть два набора мишеней: с заголовками секций и
  без них
- ~clean~ - удаляет все бинарные файлы

** Files:

- папки с утилитами ELFkickers, которая содержит утилиту sstrip - она
  позволяет обрезать таблицу заголвоков секций у исполняемых файлов
- файлов тестовых мишеней
- файла index.org, который представляет собой полное описание реализации
  проекта и объеянение всего его кода
- мэйкфайла, который компилирует вирус, мишени для него и утилиты
  ELFkickers
