#+STARTUP: showall indent hidestars

* Что это?
Это учебный файловый вирус, под Linux.

* Лицензия

GNU General Public License v.2.

* Цель

Для ознакомления с работой бинарных файлов, процессов загрузки и
линковки.

* Что делает?

Заражает первый ELF-файл, расположенный в одной с ним директории.

* Как запустить?

** Быстрый старт

Просто выполните эту последовательность команд:

#+BEGIN_SRC sh
  $ cp -r ./src/. ./
  $ make
  $ ./virus
#+END_SRC

** Старт уровня advance
- Установите Емакс - оргмод (часть емакса) нужен, чтоб сгенерировать
  файлы из литературного источника

- Выполните Alt+x и введите ~org-babel-tangle~  (можете использовать
  просто комбинацию ~C-c C-v t~ ) чтобы сгенерировать файлы.
  Вы получите:
  - исходный код вируса
  - несколько исходных файлов мишеней
  Если вы прпустите этот шаг, можете просто воспользоваться файлами из
  папки ~src~.

- make
- запустите вирус: ./virus - не волнуйтесь, он способен заражать файлы
  только текущей директории
- прочтите раздел [[*%D0%9A%D0%B0%D0%BA %D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82 %D0%B8 %D0%BA%D0%B0%D0%BA %D1%8F %D0%BC%D0%BE%D0%B3%D1%83 %D0%B2 %D1%8D%D1%82%D0%BE%D0%BC %D1%83%D0%B1%D0%B5%D0%B4%D0%B8%D1%82%D1%8C%D1%81%D1%8F][Как работает и как я могу в этом убедиться]]
- прочтите литературный исходник
- вносите предложения и поправки: комментари и пулл реквесты приветствуются

* Как работает и как я могу в этом убедиться

Выберете любой бинарник мишени. Вам нужно убедиться, что заражение
действительно состоялось. Если это так - у файла изменится адрес точки
входа.
Так выглядит точка входа мишени ~hello~ до заражения файла:

#+BEGIN_SRC sh
  $ readelf -h hello | grep Адрес

  Адрес точки входа:               0x400550
#+END_SRC

Запустите мишень, убедитесь, что она работает:

#+BEGIN_SRC sh
  $ ./hello

  Hello world!
  Current local time and date: Tue Mar  2 02:35:00 2021
#+END_SRC

Запустите вирус, вы увидите лог заражения - какие файлы вирус поптылася
заразить - и какой файл в итоге заразил:

#+BEGIN_SRC sh
  $ ./virus

  asm file: infection try
  hello file: infection try
  hello is successfully infected
#+END_SRC

Так выглядит точка входа мишени ~hello~ после заражения:

#+BEGIN_SRC sh
  $ readelf -h hello | grep Адрес

  Адрес точки входа:               0x802b28
#+END_SRC

Запустите зараженный файл, чтоб убедиться, что он не сломан:

#+BEGIN_SRC sh
  $ ./hello

  asm file: infection try
  hello file: infection try
  .#ex2.txt file: infection try
  final_version.org file: infection try
  hello_stripped file: infection try
  hello_stripped is successfully infected
  Hello world!
  Current local time and date: Tue Mar  2 02:30:18 2021
#+END_SRC

Вы видите лог заражения, какой файл в итоге был заражен, и вывод ~printf~
из самой жертвы.

Заражение прошло успешно.

Учтите, что вирус заражает ближайший незараженный файл. Поэтому если
выбранная вами мишень не заразилась сразу же, просто продолжайте
запускать вирус, пока он не дойдет до вашей мишени.

* Библиотеки и детила

Для создания мишеней для заражения проект использует утилиты ELFkickers,
чей код был скачан отсюда
http://www.muppetlabs.com/~breadbox/software/elfkickers.html и может
распространяться и модифицироваться согласно GNU GPL v.2

** Цели мэйкфайла:

- ~all~ - выполняет все ниже указанные цели кроме clean
- ~virus~ - компилирует файл вируса, если он есть
- ~sstrip~ - компилирует утилиты ELFkickers
- ~victims~ - компилирует все тестовые мешени по два раза, чтоб дубликат
каждой мишени можно было стрипнуть
- ~stripped_victims~ удаляет заголвоки секций из каждого дубликата
  мишени. Таким образом есть два набора мишеней: с заголовками секций и
  без них
- ~clean~ - удаляет все бинарные файлы

** Files:

- папки с утилитами ELFkickers, которая содержит утилиту sstrip - она
  позволяет обрезать таблицу заголвоков секций у исполняемых файлов
- файлов тестовых мишеней
- файла index.org, который представляет собой полное описание реализации
  проекта и объеянение всего его кода
- мэйкфайла, который компилирует вирус, мишени для него и утилиты
  ELFkickers
